# Wajib: Nama tema yang sudah Anda pilih
theme: jekyll-theme-minimal

# Judul utama situs Anda
title: Anjani Maulaya Nunqaf

# Deskripsi singkat (akan muncul di bawah judul)
description: Ringkasan penelitian, publikasi, dan proyek Machine Learning.
