# Wajib: Nama tema yang sudah Anda pilih
theme: jekyll-theme-minimal

# Judul utama situs Anda
title: Anjani Maulaya Nunqaf

# Deskripsi singkat (akan muncul di bawah judul)
description: Electronical and Instrumentation Master's Student at Gadjah Mada University
